### ISSUE TITLE
Use at_ prefix for category methods

### ISSUE THREAD

**Issue by duemunk** [vincilbishop/XCAsyncTestCase#5]
``` objc
- (void)waitForStatus:(XCTAsyncTestCaseStatus)status timeout:(NSTimeInterval)timeout;
- (void)waitForTimeout:(NSTimeInterval)timeout;
- (void)notify:(XCTAsyncTestCaseStatus)status;
```

becomes

``` objc
- (void)at_waitForStatus:(XCTAsyncTestCaseStatus)status timeout:(NSTimeInterval)timeout;
- (void)at_waitForTimeout:(NSTimeInterval)timeout;
- (void)at_notify:(XCTAsyncTestCaseStatus)status;
```

**Comment by carlj** [comment]
what should be the reason for that naming convention?

**Comment by vincilbishop** [comment]
I think @duemunk is right. a prefix wouldn't be a bad idea. 

When applying categories to widely used classes (like XCTest) it's a good idea to have the option to prefix method names in case another library in use has also added the same method names in a category. In that case results would be unpredictable and you would not know which method would be chosen by the compiler.

Not sure what it should be... xc_  or xct_? Where does at_ come from.... @akisute the original author of the library? I'm ok with that :)

Not sure there is an exact convention, but I usually try to start guessing with the naming prefix of the library if the author has used that pattern, that's usually convenient to make the come up in intellisense. Can't remember any convention in objective-c docs for this in particular, might have just grown out of necessity from the community.

I have seen a good implementation of that here: https://github.com/magicalpanda/MagicalRecord/blob/develop/MagicalRecord/CoreData%2BMagicalRecord.h#L11

Note the #ifdef MR_SHORTHAND. Defining that variable gives the option of having the prefixes removed. I would take the opposite approach and give the shorthand by default, and allow an option to remove it.

**Comment by duemunk** [comment]
@premosystems explains it very well. It is just best practice for categories in Objective-C. 

The `at_` was simply from `AsyncTest`, but anything will do (`xca_`, `atc_`, `asy_`). Using the authors credentials is a good approach as well e.g. `aki_`.

I'm not a big fan of the `MR_Shorthand` way, since it allows (read: encourages) bad practice.

**Comment by vincilbishop** [comment]
Well, you know what they say, the best programmers are the lazy ones,
hahaha. 

From:  Tobias Due Munk notifications@github.com
Reply-To:  premosystems/XCAsyncTestCase
<reply+i-32356872-01a2f7e5e7aa54b0b34e2456fad61ae567c3b8c0-775848@reply.gith
ub.com>
Date:  Friday, June 13, 2014 at 7:24 AM
To:  premosystems/XCAsyncTestCase XCAsyncTestCase@noreply.github.com
Cc:  Vincil Bishop info@premosystems.com
Subject:  Re: [XCAsyncTestCase] Use at_ prefix for category methods (#5)

@premosystems https://github.com/premosystems  explains it very well. It
is just best practice for categories in Objective-C.

The at_ was simply from AsyncTest, but anything will do (xca_, atc_, asy_).
Using the authors credentials is a good approach as well e.g. aki_.

I'm not a big fan of the MR_Shorthand way, since it allows (read:
encourages) bad practice.

‹
Reply to this email directly or view it on GitHub
<https://github.com/premosystems/XCAsyncTestCase/issues/5#issuecomment-46004
794> .

**Comment by carlj** [comment]
@duemunk would you like to create a pull request, with a default shorthand macro, for this?

**Comment by vincilbishop** [comment]
To change to prefixed category methods, we need to not break previous
implementations. That is why I would suggest to make shorthand the default,
and if the user has a problem then allow them to use the prefixed methods
with a preprocessor mechanism.

Let me know if you agree and that makes sense.

Can anyone supply a reference to Apple Objective-C documentation (or any
other documentation) that gives guidance for this convention? I am not aware
of guidance from Apple.

From:  Carl Jahn notifications@github.com
Reply-To:  premosystems/XCAsyncTestCase
<reply+i-32356872-01a2f7e5e7aa54b0b34e2456fad61ae567c3b8c0-775848@reply.gith
ub.com>
Date:  Friday, June 13, 2014 at 8:40 AM
To:  premosystems/XCAsyncTestCase XCAsyncTestCase@noreply.github.com
Cc:  Vincil Bishop info@premosystems.com
Subject:  Re: [XCAsyncTestCase] Use at_ prefix for category methods (#5)

@duemunk https://github.com/duemunk  would you like to create a push, with
a default shorthand macro, for this?

‹
Reply to this email directly or view it on GitHub
<https://github.com/premosystems/XCAsyncTestCase/issues/5#issuecomment-46011
951> .

**Comment by carlj** [comment]
here we go: [Avoid Category Method Name Clashes](https://developer.apple.com/library/ios/documentation/cocoa/conceptual/ProgrammingWithObjectiveC/CustomizingExistingClasses/CustomizingExistingClasses.html#//apple_ref/doc/uid/TP40011210-CH6-SW4)

> Because the methods declared in a category are added to an existing class, you need to be very careful about method names.
> 
> If the name of a method declared in a category is the same as a method in the original class, or a method in another category on the same class (or even a superclass), the behavior is undefined as to which method implementation is used at runtime. This is less likely to be an issue if you’re using categories with your own classes, but can cause problems when using categories to add methods to standard Cocoa or Cocoa Touch classes.

**Comment by carlj** [comment]
@premosystems could you also close this issue regarding https://github.com/premosystems/XCAsyncTestCase/commit/cdb25a6ae882d101e6b205db232a17624b786aa6 ?

**Comment by vincilbishop** [comment]
Hey @carlj email me, I have a few items to share with you.
